{% set name = "bio-jtools" %}
{% set version = "0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/jrhawley/bio-jtools.git
  git_rev: {{ version }}

build:
  number: 0
  entry_points:
    - jtoos=jtools._cli:main
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - numpy
    - pandas
    - pip
    - pybedtools
    - python
    - seaborn
    - tqdm
  run:
    - bedtools
    - numpy
    - pandas
    - pybedtools
    - python
    - seaborn
    - tqdm

test:
  imports:
    - jtools.multijaccard

  commands:
    - jtools --help

about:
  home: http://github.com/jrhawley/bio-jtools
  license: GPLv3
  license_family: GPL3
  license_file: LICENSE
  summary: Various bioinformatics tools in one package
  doc_url: https://bed-jaccard.readthedocs.io/en/latest/
  dev_url: http://github.com/jrhawley/bio-jtools

extra:
  recipe-maintainers:
    - jrhawley
